name: bmy

on:
  push:
    branches:
      - main # 根据实际情况调整触发分支

jobs:
  deploy-bmy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy bmy project to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./30515245/bmy/index
          destination_dir: /bmy # 部署到 GitHub Pages 的子目录

  deploy-yqh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy yqh project to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./30515245/yqh/index
          destination_dir: /yqh # 部署到 GitHub Pages 的另一个子目录